#!/usr/bin/env python2

import sys
import ast
import shlex
import os
import subprocess
from emacsclient import EmacsClient

if __name__ == '__main__':
    import argparse
    import fileinput

    parser = argparse.ArgumentParser("Review diffs generated by running compare_progs")
    parser.add_argument("-t","--tests", action='store_true', help="Assume input is list of test files (*.test)")
    parser.add_argument("files", metavar='FILE', nargs="*", help="File name to read numbers from")

    args = parser.parse_args()

    ec = EmacsClient()

    for srcfile in map(str.rstrip, fileinput.input(args.files)):
        if not args.tests:
            tfile = '.'.join([srcfile,'test'])
        else:
            tfile = srcfile
        try:
            test = None
            with open(tfile, 'rb') as f:
                test = ast.literal_eval(f.read())
            
            sys.stderr.write("Reviewing {}\n".format(f.name))
            ec.open_file(test['diff'],nowait=True)
            ec.open_file(os.path.join(test['cwd'],test['path']))
            ec.kill_all()

        except IOError as e:
            sys.stderr.write("{}: IOError {}\n".format(tfile,e))
