#!/usr/bin/env python2

import sys
import ast
import shlex
import os
import subprocess

class EmacsClient:
    def __init__(self):
        self.args = ['emacsclient','--server-file','grading']
        self.buffers = []

    def open_file(self,name,**kwargs):
        args = self.args[:]
        if 'nowait' in kwargs:
            args.append('-n')
        #args.append('-e')
        #args.append("(find file {})".format(name))
        #args.append('-c')
        #args.append('-nw')
        args.append(name)
        #tmux_args = ['tmux','split-window']
        #tmux_args.extend(args)
        #print tmux_args
        ret = subprocess.check_call(args)
        self.buffers.append(os.path.basename(name))

    def kill_buffer(self,name):
        args = self.args[:]
        args.append('-e')
        args.append('(kill-buffer \"{}\")'.format(name))
        try:
            subprocess.check_call(args)
        except subprocess.CalledProcessError as e:
            pass
            
    def kill_all(self):
        for buffer in self.buffers:
            self.kill_buffer(buffer)
        self.buffers = []

if __name__ == '__main__':
    import argparse
    import fileinput

    parser = argparse.ArgumentParser("Review diffs generated by running compare_progs")
    parser.add_argument("files", metavar='FILE', nargs="*", help="File name to read numbers from")

    args = parser.parse_args()

    ec = EmacsClient()

    for srcfile in map(str.rstrip, fileinput.input(args.files)):
        tfile = '.'.join([srcfile,'test'])
        try:
            test = None
            with open(tfile, 'rb') as f:
                test = ast.literal_eval(f.read())
            
            ec.open_file(test['diff'],nowait=True)
            ec.open_file(os.path.join(test['cwd'],test['path']))
            ec.kill_all()

        except IOError as e:
            sys.stderr.write("{}: IOError {}\n".format(tfile,e))
